```{r, results=FALSE}

library(naniar)
library(scales)
library(car)
library(bestglm)
library(glmnet)

```

```{r}
# Read in data
df_cv_mice <- read.csv("imputed_data.csv", header=TRUE) #reading in the data
df_cv_mice <- subset(df_cv_mice, select = -c(1) ) #removing duplicate column
```

```{r}
# create dummy variables

library(fastDummies) #package to create dummy vars for factorized vars w/ multiple levels
df_cv_mice <- dummy_cols(
  df_cv_mice,
  select_columns = c('DLIT_AG', 'ZSN_A', 'ant_im', 'lat_im', 'inf_im', 'post_im', 'TIME_B_S', 'R_AB_1_n', 'R_AB_2_n', 'R_AB_3_n', 'NA_R_1_n', 'NA_R_2_n', 'NA_R_3_n', 'NOT_NA_1_n','NOT_NA_2_n', 'NOT_NA_3_n'  ),
  remove_first_dummy = TRUE, #avoids multicollinearity
  remove_most_frequent_dummy = FALSE,
  ignore_na = FALSE,
  split = NULL,
  remove_selected_columns = FALSE,
  omit_colname_prefix = FALSE
)

df_cv_mice <- subset(df_cv_mice,select =-c(DLIT_AG, ZSN_A, ant_im, lat_im, inf_im, post_im, TIME_B_S, R_AB_1_n, R_AB_2_n, R_AB_3_n, NA_R_1_n, NA_R_2_n, NA_R_3_n, NOT_NA_1_n,NOT_NA_2_n, NOT_NA_3_n))

```

```{r, results=FALSE}

#Straight Model
df_cv_mice_sm <- df_cv_mice
df_cv_mice_sm$FIBR_PREDS <- as.numeric(as.character(df_cv_mice_sm$FIBR_PREDS))

fit_sm <- glm(FIBR_PREDS ~ ., data=df_cv_mice_sm, family='binomial')

summary(fit_sm)

```

```{r, results=FALSE}

#Forward Selection
df_cv_mice_fs <- df_cv_mice
df_cv_mice_fs$FIBR_PREDS <- as.numeric(as.character(df_cv_mice_fs$FIBR_PREDS))

start.mod <- glm(FIBR_PREDS ~ 1, data=df_cv_mice_fs, family='binomial')
stop.mod <- formula(glm(FIBR_PREDS ~ ., data=df_cv_mice_fs, family = 'binomial'))

alpha.crit <- 0.05
fit_fs <- step(start.mod,scope=stop.mod,direction="forward",test="F",k=qchisq(1-alpha.crit,1))

summary(fit_fs)

```

```{r, results=FALSE}

#Backward Selection
df_cv_mice_bs <- df_cv_mice
df_cv_mice_bs$FIBR_PREDS <- as.numeric(as.character(df_cv_mice_bs$FIBR_PREDS))

all.mod <- glm(FIBR_PREDS ~ ., data=df_cv_mice_bs, family = 'binomial')

alpha.crit <- 0.2
fit_bs <- step(all.mod,direction="backward")

summary(fit_bs)

```

```{r}

#Random Forest
library(randomForest)
library(caret)
library(dplyr)
library(caTools)

df_cv_mice_forest <- df_cv_mice

split <- sample.split(df_cv_mice_forest, SplitRatio = 0.7) 
data_train <- subset(df_cv_mice_forest, split == "TRUE") 
data_test <- subset(df_cv_mice_forest, split == "FALSE") 


bestmtry <- tuneRF(df_cv_mice_forest,df_cv_mice_forest$FIBR_PREDS,stepFactor = 1.2, improve = 0.01, trace=T, plot= T) 

fit_forest <- randomForest(FIBR_PREDS ~.,data= df_cv_mice_forest)

```