For creating descriptive statistics of predictors for several models

```{r}
# DO NOT USE
# load in Imputed Data
imputed_data <- read.csv("imputed_data.csv", header=TRUE) #reading in the data
imputed_data <- subset(data, select = -c(1) ) #removing duplicate column
```

```{r}
# Create df for LASSO
lasso_df <- data.frame(c("Intercept", colnames(xx)), as.vector(lasso.coef)) #coefficients
 
zero_coeff_index <- which(lasso_df[,2]==0)
#creating data frame of nonzero coefficients
lasso_df <- lasso_df [-(zero_coeff_index),]
```

```{r}
# Create df for FORWARD SELECTION
fs_coeff <- fit_fs$coefficients
fs_coeff <- data.frame(fs_coeff)
fs_coeff['Predictors'] <- row.names(fs_coeff)
fs_coeff['Coefficients'] <- fs_coeff$fs_coeff
fs_coeff <- fs_coeff[-c(2),]
fs_coeff <- fs_coeff[,-c(1)]
row.names(fs_coeff) <- (1:25)
```

```{r}
# Set df
df <- fs_coeff
#df <- lasso_df
```

```{r}
#arranging them in decreasing order of absolute value
order <- order(abs(df[,2]), decreasing=TRUE) 
ordered_df <- df[order,]
colnames(df) <- c("Covariate (or Intercept)", "Coefficient")
ordered_df
```

```{r}
data_sig <- subset(df_cv_mice, select=c("FIBR_PREDS", "nr_07", "np_05", "NOT_NA_1_n", "n_r_ecg_p_06", "ritm_ecg_p_04", "K_SH_POST", "nr_03", "ant_im", "nr_11", "n_r_ecg_p_01", "NOT_NA_1_n", "ritm_ecg_p_08", "zab_leg_01", "NOT_NA_KB", "ant_im", "ant_im", "NOT_NA_1_n", "SEX", "LID_S_n", "IBS_POST", "NOT_NA_1_n", "IBS_POST", "ant_im", "AGE"))

#Descriptive stats: split into have Afib and don't have afib, see the "mode" for each
head(data_sig)
afib_yes <- data_sig[data_sig$FIBR_PREDS==1,]
afib_no <- data_sig[data_sig$FIBR_PREDS==0,]
```

```{r}
#function for writing proportions:
prop <- function (vec)
{
  vec <- as.numeric(vec)
  yes = sum(vec)
  return (yes/length(vec))
}
prop (afib_yes[,3]) #testing it on a random column

#creating a list of mean (numeric) and proportion (categorical) for each of the variables in afib_yes
afib_yes_stats = data.frame(matrix(nrow = 1, ncol = length(data_sig[1,])))  #empty matrix to include the desired descriptive stats for each covariate
colnames(afib_yes_stats) <- colnames(afib_yes)
for (i in c(1:length(colnames(data_sig))))
{
  if(i %in% c(2,41,42))
  {
    afib_yes_stats[i]<-(mean(afib_yes[,i]))
  }
  else
  {
    afib_yes_stats[i]<-(prop(afib_yes[,i]))  
  }
}


#creating a list of mean (numeric) and proportion (categorical) for each of the variables in afib_yes
afib_no_stats = data.frame(matrix(nrow = 1, ncol = length(data_sig[1,])))  #empty matrix to include the desired descriptive stats for each covariate
colnames(afib_no_stats) <- colnames(afib_no)
for (i in c(1:length(colnames(data_sig))))
{
  if(i %in% c(2,41,42))
  {
    afib_no_stats[i]<-(mean(afib_no[,i]))
  }
  else
  {
    afib_no_stats[i]<-(prop(afib_no[,i]))  
  }
}
```

```{r}
# Combine data frames
comb_df <- rbind(afib_no_stats, afib_yes_stats)

# Find top 3 significant predictors
top3_sig <- c(ordered_df[1,1], ordered_df[2,1], ordered_df[3,1])
top3_sig
```

```{r}
# NUMERIC
sig <- comb_df$'AGE'
barplot(sig, ylab = 'Mean', names.arg = c('No afib', 'afib'))

# inference test
# x_mean <- afib_no$'AGE'
# y <- afib_yes$'AGE'
# t.test(x_mean, y, alternative = "two.sided", var.equal = FALSE)
```

```{r}
# CATEGORICAL
sig <- comb_df$'nr_07'
# pie(sig[1])
# pie(sig[2])
barplot(sig, ylab = 'Proportion', names.arg = c('No afib', 'afib'))

# inference test
# x_prop <- c(sum(afib_no$'nr_07'), sum(afib_yes$'nr_07'))
# prop.test(x_prop, c(1530, 170))
```

