```{r}

library("dplyr")
df_cv_data <- read.csv("Myocardial infarction complications Database.csv")

```

```{r}
# Create data frame
learn_data <- data.frame()

# Loop through data
for(i in 1:length(df_cv_data)){
  # store index
  learn_data[i,1] <- i
  # store covariate name
  learn_data[i,2] <- colnames(df_cv_data)[i]
  
  # store 1 if contains missing data
  if(any(is.na(df_cv_data[,i])==TRUE) == TRUE){
    learn_data[i,3] <- 1
  }else{
    learn_data[i,3] <- 0
  }
  true_v <- is.na(df_cv_data[,i])
  # calculate percent missing data
  learn_data[i,4] <- round((length(true_v[true_v == TRUE])/1700)*100,1)
}

# set columns
colnames(learn_data)[1:4] <- c("index", "covariate", "contains_NA", "percent_missing")

write.csv(learn_data,"understand_missing.csv")

```

```{r}

names <- c(3:34,39:83,85,92:124)

df_cv_data <- mutate(df_cv_data,across(names,as.factor))

```

```{r}

mice_methods <- c()

for(i in 1:length(df_cv_data)){
  if(is.numeric(df_cv_data[,i]) == TRUE){
    mice_methods[i] <- "pmm"
  }else if(is.numeric(df_cv_data[,i]) == FALSE){
    if(length(unique(df_cv_data[,i])) == 2){
      mice_methods[i] <- "logreg"
    }else{
      mice_methods[i] <- "polyreg"
    }
  }
}

```

```{r}

library(mice)

df_cv_2 <- subset(df_cv_data,select=-c(KFK_BLOOD,IBS_NASL,S_AD_KBRIG,D_AD_KBRIG))

  my_imp <- mice(data=df_cv_2,m=1,method='pmm')
  
for(i in 2:length(df_cv_2)){
  temp_change <- my_imp$imp[[i]]
  indicies <- which(is.na(df_cv_2[i]))
  counter <- 0
  for(j in indicies){
    counter <- counter+1
    df_cv_2[j,i] <- temp_change[counter,1]
  }
}

```

```{r}

df_cv_3 <- subset(df_cv_2,select=-c(PREDS_TAH,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,ZSN,REC_IM,P_IM_STEN,LET_IS))

```
