```{r}

library("dplyr")
df_cv_data <- read.csv("Myocardial infarction complications Database.csv")
df_cv_data[271,91] <- NA

```

```{r}

#Correlation plot cor.test library(corplot)
#Cohesively argue
#Look for biological significance

learn_data <- data.frame()

for(i in 1:length(df_cv_data)){
  learn_data[i,1] <- i
  learn_data[i,2] <- colnames(df_cv_data)[i]
  if(any(is.na(df_cv_data[,i])==TRUE) == TRUE){
    learn_data[i,3] <- 1
  }else{
    learn_data[i,3] <- 0
  }
  true_v <- is.na(df_cv_data[,i])
  learn_data[i,4] <- round((length(true_v[true_v == TRUE])/1700)*100,1)
}

colnames(learn_data)[1:4] <- c("index", "covariate", "contains_NA", "percent_missing")

write.csv(learn_data,"C:/Users/manoj/SIBS Final Project/Data/understand_missing.csv")

```

```{r}

names <- c(3:34,39:83,85,92:124)

df_cv_data <- mutate(df_cv_data,across(names,as.factor))

df_cv_sub <- subset(df_cv_data,select=-c(ID,KFK_BLOOD,IBS_NASL,S_AD_KBRIG,D_AD_KBRIG,PREDS_TAH,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,ZSN,REC_IM,P_IM_STEN,LET_IS))

```

```{r}

library(mice)

my_imp <- mice(data=df_cv_sub,m=1,method='pmm')
  
df_cv_mice <- complete(my_imp)

```

```{r}

library(corrplot)
library(caret)

df_cv_mice_sm <- df_cv_mice
df_cv_mice_sm$FIBR_PREDS <- as.numeric(as.character(df_cv_mice_sm$FIBR_PREDS))

fit_sm <- glm(FIBR_PREDS ~ ., data=df_cv_mice_sm, family='binomial')

corrplot(cor(model.matrix(fit_sm)[,-1], method = c("pearson", "kendall", "spearman")),method = "color")

findCorrelation(cor(model.matrix(fit_sm)[,-1]), cutoff=0.8, names=TRUE)

df_cv_mice <- subset(df_cv_mice,select=-S_AD_ORIT)

```

```{r}

write.csv(df_cv_mice,"C:/Users/manoj/SIBS Final Project/Data/imputed_data.csv")

```